import streamlit as st

st.set_page_config(page_title="About - Happy Mind", page_icon="🧠", layout="wide")

if "logged_in" not in st.session_state:
    st.switch_page("app.py")

st.title("🌿 About Happy Mind")

st.write("""
**Happy Mind** is a mental health awareness and lifestyle analysis
application designed to help individuals understand how daily habits
such as sleep, screen time, workload, and social interaction can
influence mental well-being.

The goal of this platform is to promote mental health awareness,
encourage healthy lifestyle habits, and provide educational
resources about common psychological conditions.
""")

st.divider()

# ---------- PURPOSE ----------

st.header("🎯 Purpose of the Application")

st.write("""
Mental health challenges such as stress, anxiety, depression,
and burnout are increasingly common among students and
working professionals. Many people experience these
conditions without recognizing the early warning signs.

Happy Mind aims to help users reflect on their daily
habits and understand how lifestyle factors may affect
their mental health.
""")

st.divider()

# ---------- HOW SYSTEM WORKS ----------

st.header("⚙ How the System Works")

st.write("""
Happy Mind analyzes several lifestyle factors that are
commonly associated with mental health.

The system evaluates information such as:

• Sleep duration  
• Screen time usage  
• Study or work hours  
• Exercise habits  
• Social interaction levels  
• Academic or work pressure  
• Time management ability  

Based on these inputs, the system estimates possible
levels of stress, anxiety, depression, and burnout.
""")

st.divider()

# ---------- FEATURES ----------

st.header("🚀 Key Features")

col1, col2 = st.columns(2)

with col1:

    st.subheader("📊 Mental Health Dashboard")

    st.write("""
The dashboard visualizes lifestyle data using charts
and metrics to help users observe patterns related
to sleep, screen time, and workload.
""")

    st.subheader("🤖 Mental Health Prediction")

    st.write("""
The prediction system analyzes lifestyle factors
and estimates potential mental health risks such
as stress, anxiety, depression, and burnout.
""")

with col2:

    st.subheader("📚 Education Center")

    st.write("""
The education center provides detailed information
about mental health topics including stress,
anxiety, depression, burnout, sleep health,
digital well-being, and mindfulness.
""")

    st.subheader("👤 Personal Profile")

    st.write("""
Users can create a personal profile where
lifestyle and behavioral data are stored
to generate insights and reports.
""")

st.divider()

# ---------- TECHNOLOGY ----------

st.header("💻 Technology Used")

st.write("""
Happy Mind is built using modern data science and
web application technologies.

Main technologies include:

• Python Programming  
• Streamlit Framework  
• Pandas for data processing  
• Data visualization tools for dashboards
""")

st.divider()

# ---------- DISCLAIMER ----------

st.header("⚠ Disclaimer")

st.write("""
Happy Mind is designed for **educational and awareness purposes only**.
The insights and predictions generated by this system are not
medical diagnoses.

If individuals experience persistent emotional distress,
they are encouraged to seek professional help from
licensed psychologists, counselors, or healthcare providers.
""")

st.divider()

# ---------- DEVELOPER ----------

st.header("👨‍💻 Developer")

st.write("""
**Mugundhan G** is a Bachelor of Computer Applications (BCA)
student specializing in **Data Science** with an interest
in building data-driven applications and exploring
artificial intelligence.

The **Happy Mind** project was developed as a learning
initiative to combine technology, data analysis, and
mental health awareness.

**Skills:** Python, Streamlit, Data Analysis, Data Visualization,
Basic Machine Learning.
""")

# ---------- SIDEBAR ----------

st.sidebar.write("Logged in as:")
st.sidebar.success(st.session_state["user_email"])

if st.sidebar.button("Logout"):
    st.session_state.clear()
    st.switch_page("app.py")